version: '3.1'
services:
  php-cli:
    build: docker/.
    working_dir: /app
    volumes:
      - '.:/app'
      - './docker/overrides.ini:/usr/local/etc/php/conf.d/overrides.ini'
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
